// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nvzuwnysknmrfzpzmtwp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im52enV3bnlza25tcmZ6cHptdHdwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4MzgxNjIsImV4cCI6MjA2NDQxNDE2Mn0.uORrJhohuYDuTEY8sEtNdJbRQYgyDs2tDTY1uyQlmwA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);